# Generated by Django 3.2.13 on 2022-08-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_blockednumber_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockednumber',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
