# Generated by Django 3.2.14 on 2022-12-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220906_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsItem',
            fields=[
                ('sms_id', models.IntegerField(primary_key=True, unique=True)),
                ('user_email', models.CharField(max_length=50)),
                ('recipient_phone_number', models.CharField(max_length=50)),
                ('sender_phone_number', models.CharField(max_length=50)),
                ('sms_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
