# Generated by Django 3.2.14 on 2022-12-20 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_smsitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsitem',
            name='sms_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
