# Generated by Django 3.2.13 on 2022-08-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220717_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='external_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='external_phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
