# Generated by Django 3.2.13 on 2022-08-28 23:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20220825_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_reset_request_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_request_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='external_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
