# Generated by Django 3.2.13 on 2022-09-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_emailchangeauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_wizard_step',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='selected_plan',
            field=models.IntegerField(default=0),
        ),
    ]
