# Generated by Django 3.2.14 on 2022-12-20 06:18

from django.db import migrations

import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20220907_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
